### ISSUE TITLE
If I utter "play" what does it do? skill contention.

### ISSUE THREAD

**Issue by neil969** [ejstacey/skill-subsonic-media#4]
Hi,
Is it possible to change the "play" command to something customised or have it recognise "subsonic" as a substitute for the word play? 
The reason:
The Subsonic skill was working wonderfully until... The "youtube" skill was fixed! 
Now when I say "play XXXXXXXX" it is intercepted by the youtube skill , and goes on to search youtube for the song - which works. It had been broken for a while, and I forgot it was there :) 
Now I can't get to the subsonic library unless I uninstall the youtube skill, but I am greedy and want both :) 
Thanks for this Subsonic skill too, by the way! I an @a_user on the mycroft chat if you want more info

**Comment by ejstacey** [comment]
This is a bigger issue Mycroft has to fix somehow (no idea how), but in the meantime, I've added "sub play" as well as "play", so you should be able to say "sub play <whatever>" and have the subsonic skill handle it.

Thanks!

(commit ec0f83206d134bae73ea4e70e2e3485ac9a7d576)

**Comment by neil969** [comment]
thanks ;)
